### ISSUE TITLE
多义词的处理

### ISSUE THREAD

**Issue by TaylorVictor** [koala-222/baiduBaikeSpider#1]
请问你这个解析中是不是忽略了对多义词的处理？

**Comment by Hao-Kailong** [comment]
hello，这个代码是没有处理一词多义的情况的。比如“苹果”对应的“水果”和“公司”这种现象，是没有特殊处理的。

代码只是做了页面的爬取工作，把html页面整个直接存储到硬盘，并且简单地提取一些元信息，例如标题、url、二级标题、id编号等，写入csv文件中。

对于数据的处理和分析工作，可以在整个爬取结束后进行。

**Comment by koala-222** [comment]
> 请问你这个解析中是不是忽略了对多义词的处理？

hello，这个代码是没有处理一词多义的情况的。比如“苹果”对应的“水果”和“公司”这种现象，是没有特殊处理的。

代码只是做了页面的爬取工作，把html页面整个直接存储到硬盘，并且简单地提取一些元信息，例如标题、url、二级标题、id编号等，写入csv文件中。

对于数据的处理和分析工作，可以在整个爬取结束后进行。

**Comment by TaylorVictor** [comment]
好的谢谢，明白了，那么你使用的是快代理的哪个方案呢？

**Comment by TaylorVictor** [comment]
我看你博客中说是用174G的内存（你这个内存是指爬虫运行需要的内存？），你这个线性的遍历为什么会需要这么多内存呢？

**Comment by koala-222** [comment]
> 好的谢谢，明白了，那么你使用的是快代理的哪个方案呢？

就是付费的基础版本

**Comment by koala-222** [comment]
> 我看你博客中说是用174G的内存（你这个内存是指爬虫运行需要的内存？），你这个线性的遍历为什么会需要这么多内存呢？

不是的，机器内存大小是这么大，运行时并不会全部占满
